title: SAP on AWS 
description: Your guide for SAP on AWS 

theme: just-the-docs

url: https://saponaws.org

aux_links:
  SAP on AWS Book: https://book.saponaws.org


 # Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/aws-sap.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/aws_sap_icon.ico"

 
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


